(function(){
  var out$ = typeof exports != 'undefined' && exports || this;
  jQuery(function(){
    var width, height, engine, menu, x$, startgame, music, scene, y$, panda, z$, logo, z1$, block1, z2$, block2, z3$, block3, z4$, block4, z5$, block6, z6$, fps;
    width = jQuery(window).width();
    height = jQuery(window).height();
    engine = new Darkcore.Engine(width, height, 'Hi Panda!');
    menu = new Darkcore.Scene('menu', engine);
    x$ = startgame = new Darkcore.Sprite.Text(menu, "Start Game", 100, 25, engine.width / 2, engine.height / 2);
    x$.id = "start";
    x$.setColor(255, 0, 0);
    x$.setTextColor(255, 255, 255);
    x$.setTextAlign('center');
    music = new Darkcore.Sound('resources/Control_Alt_Deus_-_01_-_Control.mp3');
    menu.addSound(music);
    music.play();
    scene = new Darkcore.Scene('game', engine);
    scene.gamestate = {
      blocks: []
    };
    y$ = panda = new Game.Panda(scene);
    y$.x = 100;
    y$.y = 200;
    y$.velocity_x = 0.5;
    z$ = logo = new Game.Logo(scene);
    z$.setText("Hi! Panda");
    z$.x = 300;
    z$.y = 300;
    z$.scale_x = 2.0;
    z$.scale_y = 2.0;
    z1$ = block1 = new Game.Grass(scene, 256, 192, 500, 0);
    z1$.id = "block1";
    scene.gamestate.blocks.push(block1);
    z2$ = block2 = new Darkcore.Sprite(scene, 100, 15, 100, 50);
    z2$.id = "block2";
    z2$.setColor(0, 255, 0);
    scene.gamestate.blocks.push(block2);
    z3$ = block3 = new Darkcore.Sprite(scene, engine.width, 20, engine.width / 2, 0);
    z3$.id = "block3";
    z3$.setColor(50, 50, 50);
    scene.gamestate.blocks.push(block3);
    z4$ = block4 = new Darkcore.Sprite(scene, 75, 20, 320, 10);
    z4$.id = "block4";
    z4$.setColor(50, 50, 50);
    scene.gamestate.blocks.push(block4);
    z5$ = block6 = new Darkcore.Sprite(scene, 75, 20, 200, 85);
    z5$.id = "block6";
    z5$.setColor(50, 50, 50);
    scene.gamestate.blocks.push(block6);
    z6$ = fps = new Game.FPS(scene);
    z6$.x = 400;
    z6$.y = 100;
    engine.run();
    return out$.engine = engine = engine;
  });
}).call(this);
